### ISSUE TITLE
Module-Info

### ISSUE THREAD

**Issue by JhonnySalles** [Dansoftowner/FXTaskbarProgressBar#2]
Thanks for all the updates on your project, i am very grateful.

I tried to migrate to use your project by maven, but it presents conflicts when used by modules, due to not being able to obtain the specific name, so I returned to using your jar in the Referenced Libraries.

By default, when you don't have the module configuration file in your projects, java tends to use the name of the project or class, but I couldn't find the correct name for it to work with the module configuration.

If possible, I would like you to add Module-Info in your project, as this way I can configure the module correctly through the name given in this file.

![image](https://user-images.githubusercontent.com/43912638/85477411-a36d7880-b590-11ea-8e60-1edf30a5ecbb.png)

![image](https://user-images.githubusercontent.com/43912638/85477518-d879cb00-b590-11ea-8e15-d34022128364.png)

**Comment by Dansoftowner** [comment]
Hi!

Now you can add `requires nativejavafx.taskbar` to your `module-info` but you should use the latest, `v11.2.7` version of the library.  All information is in the [README](https://github.com/Dansoftowner/FXTaskbarProgressBar/blob/master/README.md).

Thanks for your comment!
If you have more issues don't hesitate to contact me!

**Comment by JhonnySalles** [comment]
Thank you very much for the work, I'll be updating.
